### ISSUE TITLE
Error: ImportError: No module named 'six'

### ISSUE THREAD

**Issue by dnc-msimons** [fgmacedo/django-export-action#7]
* Django Export Action version: 0.1.1
* Django version: 1.10
* Python version: 2.7.10
* Operating System: macOS Sierra 10.12.5

### Description

Installing via README and test export functionality

### What I Did

```
(venv) Michaels-MacBook-Pro:dn-sql-catalog msimons$ pip install django-export-action
Collecting django-export-action
  Using cached django_export_action-0.1.1-py2.py3-none-any.whl
Collecting openpyxl (from django-export-action)
Collecting et-xmlfile (from openpyxl->django-export-action)
Collecting jdcal (from openpyxl->django-export-action)
Installing collected packages: et-xmlfile, jdcal, openpyxl, django-export-action
Successfully installed django-export-action-0.1.1 et-xmlfile-1.0.1 jdcal-1.3 openpyxl-2.4.8

/Users/msimons/Code/dn-sql-catalog/venv/bin/python /Users/msimons/Code/dn-sql-catalog/manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x10a67b758>
Traceback (most recent call last):
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/msimons/Code/dn-sql-catalog/dn_sql_catalog/urls.py", line 23, in <module>
    url(r'export_action/', include("export_action.urls", namespace="export_action")),
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/export_action/urls.py", line 3, in <module>
    from .views import AdminExport
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/export_action/views.py", line 11, in <module>
    from . import report
  File "/Users/msimons/Code/dn-sql-catalog/venv/lib/python2.7/site-packages/export_action/report.py", line 20, in <module>
    from six import BytesIO, text_type
ImportError: No module named six



running 'pip install six' and Django app goes back to running fine.  But might want to include 'six' in the prerequisites?

```

**Comment by fgmacedo** [comment]
Hi @dnc-msimons, thanks for your report!

Yeah, Its a requirement. But since Django is already a requirement, I could use the `six` module bundled with Django, so if It works, we don't need to explicitly require `six`:

```
from django.utils import six
```

What do you think?

**Comment by dnc-msimons** [comment]
If that works for you, it works for me.   Just trying to do my part to report the issue as it came up when I tried to follow the readme instructions.
